// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsaD83f4iLeElSlrMrtaR79VZAEI2D-kU',
    appId: '1:725944279887:web:e83a7ed4dd285e90a31b3a',
    messagingSenderId: '725944279887',
    projectId: 'emassaha',
    authDomain: 'emassaha.firebaseapp.com',
    storageBucket: 'emassaha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-1rR9eoOmglYD_9_mA4s37OODC1O7ihQ',
    appId: '1:725944279887:android:f8b552227c10ef1fa31b3a',
    messagingSenderId: '725944279887',
    projectId: 'emassaha',
    storageBucket: 'emassaha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg3mlRDmhyEHu5JzpaRFI7AmVOBp0aZWc',
    appId: '1:725944279887:ios:ab9ed01edd5f7084a31b3a',
    messagingSenderId: '725944279887',
    projectId: 'emassaha',
    storageBucket: 'emassaha.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg3mlRDmhyEHu5JzpaRFI7AmVOBp0aZWc',
    appId: '1:725944279887:ios:ab9ed01edd5f7084a31b3a',
    messagingSenderId: '725944279887',
    projectId: 'emassaha',
    storageBucket: 'emassaha.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsaD83f4iLeElSlrMrtaR79VZAEI2D-kU',
    appId: '1:725944279887:web:011e24aabfac3029a31b3a',
    messagingSenderId: '725944279887',
    projectId: 'emassaha',
    authDomain: 'emassaha.firebaseapp.com',
    storageBucket: 'emassaha.firebasestorage.app',
  );
}
